### ISSUE TITLE
无法动态可视化训练数据

### ISSUE THREAD

**Issue by zhouhao-learning** [mtyylx/MLND#1]
您好！我在使用猫狗数据训练的时候，按照您的步骤训练了两次保存下来权重，然后再打开权重，然后用cv2读取一张图片，运行您的GetCam函数，但是却得到了错误提示
`io/opencv/modules/imgproc/src/colormap.cpp:517: error: (-5) cv::ColorMap only supports source images of type CV_8UC1 or CV_8UC3 in function operator()
`
请问这个主要是什么原因导致的呢，是我的软件包跟您的版本不一样吗？请给予指导，谢谢！

**Comment by mtyylx** [comment]
这个报错应该是你的cam数据没有满足colormap的格式要求（cv_8uc1）导致的。getCAM里面有把cam的矩阵转型为np.uint8的代码，就是为了确保cam的数据是满足cv_8uc1的。
```
# Format as CV_8UC1 (as applyColorMap required)
cam_resize = 255 * cam_resize
cam_resize = cam_resize.astype(np.uint8)
```

**Comment by CrunchyBiscuits** [comment]
> 您好！我在使用猫狗数据训练的时候，按照您的步骤训练了两次保存下来权重，然后再打开权重，然后用cv2读取一张图片，运行您的GetCam函数，但是却得到了错误提示
> `io/opencv/modules/imgproc/src/colormap.cpp:517: error: (-5) cv::ColorMap only supports source images of type CV_8UC1 or CV_8UC3 in function operator() `
> 请问这个主要是什么原因导致的呢，是我的软件包跟您的版本不一样吗？请给予指导，谢谢！

您好，请问这个问题有解决么，我现在也碰到同样的报错，而且已经通过np.uint8转过了
