### ISSUE TITLE
必须是网络中有global average pooling吗？

### ISSUE THREAD

**Issue by haoranD** [mtyylx/MLND#2]
你好，我也是在udacity中学习过的学员，所以有幸认识你。我想问一下，这个CAM它对于网络或者网络中的结构有什么要求或者限制吗，谢谢 刚刚开始了解tf和CAN。之前一直是用的caffe。非常感谢百忙中抽时间回答

**Comment by mtyylx** [comment]
可以了解下 [Grad-CAM](https://arxiv.org/abs/1610.02391)，这个就不需要强制 GAP 了。
